version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: tron-payment-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - payment-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb://admin:password@localhost:27017/admin --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Payment Gateway API service
  # payment-api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: tron-payment-api
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongodb
  #   environment:
  #     - NODE_ENV=production
  #     - PORT=3000
  #     - MONGO_URI=mongodb://admin:password@mongodb:27017/tron-payment-gateway?authSource=admin
  #     - TRON_FULL_HOST=https://api.trongrid.io
  #     - TRON_PRIVATE_KEY=${TRON_PRIVATE_KEY}
  #     - MAIN_WALLET_ADDRESS=${MAIN_WALLET_ADDRESS}
  #     - USDT_CONTRACT_ADDRESS=${USDT_CONTRACT_ADDRESS}
  #   networks:
  #     - payment-network
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "10m"
  #       max-file: "3"

  # Mongo Express for database management (optional, only for development)
  mongo-express:
    image: mongo-express:latest
    container_name: tron-payment-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - payment-network
    profiles:
      - dev

volumes:
  mongodb_data:
    name: tron-payment-mongodb-data

networks:
  payment-network:
    driver: bridge
    name: tron-payment-network 